name: create draft release
on:
  push:
    branches:
      - main
    paths:
      - 'articles/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload article to Hatena Blog
        env:
          HATENA_API_KEY: ${{ secrets.HATENA_API_KEY }}
        run: |
          CHANGED_MD_FILE=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.md$' || true)
          if [ -n "$CHANGED_MD_FILE" ]; then
            echo "Uploading ${CHANGED_MD_FILE} to Hatena Blog"
            bash scripts/upload.sh "${HATENA_API_KEY}" "${CHANGED_MD_FILE}"
          fi
